# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
  #  - FOO={{ .Env.FOOBAR }}
  #  - IMAGE_COPY={{ .Env.IMAGE }}
  - IMAGE=yurikrupnik/fiber-mongo
project_name: fiber-mongo
before:
  hooks:
    - go mod tidy
    - go test -v ./...
#    - echo $IMAGE_COPY
#    - echo ${IMAGE_COPY}
#    - echo $IMAGE
#    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      #      - windows
      - darwin
    goarch:
      #      - 386
      - amd64
      #      - arm
      - arm64
    #    goarm:
    #      - 6
    #      - 7
    binary: fiber-mongo
#    hooks:
#      pre:
#        - ls -a
#        - second-script.sh
#      post:
#        - ls -a
#        - codesign -project="{{ .ProjectName }}" "{{ .Path }}"
#archives:
#  -
#    name_template: aris
#    builds:
#      - default
#    meta: true
#  - replacements:
#      darwin: Darwin
#      linux: Linux
##      windows: Windows
##      386: i386
#      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
#  name_template: "{{ .ProjectName }}_{{ .Version }}" # {{ .Os }}_{{ .Arch }}


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

release:
  #  draft: true
  prerelease: auto
  name_template: "yurikrupnik/{{ .ProjectName }}:{{ .Tag }}"
  disable: false
  mode: append
  gitea:
    owner: yurikrupnik
    name: hello
  #  ids:
  #    - foo
  #    - bar

  header: |
    ## Some title ({{ .Date }})
    docker hub: yurikrupnik/fiber-mongo:{{ .Tag }}
    Docker Hub: [image](yurikrupnik/fiber-mongo:{{ .Tag }})
    Welcome to this new release!

    # Footer template for the release body.
    # Defaults to empty.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!


dockers:
  -
    image_templates:
      - "yurikrupnik/{{ .ProjectName }}:{{ .Tag }}"
      - "yurikrupnik/{{ .ProjectName }}:{{ .ShortCommit }}"
    #      - "yurikrupnik/{{ .ProjectName }}:{{ .Tag }}-amd64"
    #      - "yurikrupnik/{{ .ProjectName }}:{{ .ShortCommit }}-amd64"
    #    build_flag_templates:
    #      - "--push"
    #      - "--label=org.opencontainers.image.created={{.Date}}"
    #      - "--label=org.opencontainers.image.title={{.ProjectName}}"
    #      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    #      - "--label=org.opencontainers.image.version={{.Version}}"
    #      - "--platform=linux/amd64"
    use: buildx
    #    goarch: amd64
    #      - linux
    #      - windows
    #      - darwin
    #    goarch:
    #      - 386
    #      - amd64
    #      - arm
    #      - arm64
    dockerfile: Dockerfile
#  -
#    image_templates:
#      - "yurikrupnik/{{ .ProjectName }}:{{ .Tag }}"
##      - "yurikrupnik/{{ .ProjectName }}:{{ .Tag }}-arm64"
##      - "yurikrupnik/{{ .ProjectName }}:{{ .ShortCommit }}-arm64"
#    use: buildx
#    goarch: arm64
#    dockerfile: Dockerfile
#    build_flag_templates:
#      - "--pull"
#      - "--label=org.opencontainers.image.created={{.Date}}"
#      - "--label=org.opencontainers.image.title={{.ProjectName}}"
#      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#      - "--label=org.opencontainers.image.version={{.Version}}"
#      - "--platform=linux/arm64"
#docker_manifests:
#  -
#    name_template: yurikrupnik/{{ .ProjectName }}:{{ .Tag }}
#    image_templates:
#      - yurikrupnik/{{ .ProjectName }}:{{ .Tag }}
#      - yurikrupnik/{{ .ProjectName }}:{{ .Tag }}